// import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import NavigationMenu from "@/components/NavigationMenu";
import { Roboto } from "next/font/google"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: "e-Yoga",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body className={`${roboto.className} antialiased flex flex-col min-h-screen`}>
                <NavigationMenu />
                <main className="flex-grow">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
